---
- name: Install bat package
  apt:
    name: bat
    state: present

- name: Create local bin directory if not exists
  ansible.builtin.file:
    path: "{{ user_home_dir_path }}/.local/bin"
    state: directory

- name: Create symlink to bat binary file
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ user_home_dir_path }}/.local/bin/bat"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
